CREATE TABLE IF NOT EXISTS `__TABLE_PREFIX__dscomments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `ds_id` int(11) unsigned NOT NULL,
  `document_id` int(11) unsigned NOT NULL DEFAULT '0',
  `page_url` tinytext DEFAULT '',
  `page_title` varchar(255) DEFAULT '',
  `author` tinytext NOT NULL,
  `author_email` varchar(100) NOT NULL DEFAULT '',
  `author_url` varchar(200) NOT NULL DEFAULT '',
  `author_IP` varchar(100) NOT NULL DEFAULT '',
  `created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `content` text NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `user_id` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `document_id` (`document_id`),
  KEY `ds_id` (`ds_id`, `status`),
  KEY `created_on` (`created_on`),
  KEY `parent_id` (`parent_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;
